const REGISTER = 'REGISTER';
const LOGIN = 'LOGIN';
const REMOVE_USER = 'REMOVE_USER';
const EDIT_USER = 'EDIT_USER';
const ADD_LIST = 'ADD_LIST';
const ADD_PLANT = 'ADD_PLANT';
const REMOVE_PLANT = 'REMOVE_PLANT';
const DELETE_LIST = 'DELETE_LIST';
const SEARCH_PLANTS = 'SEARCH_PLANTS';

export { REGISTER, LOGIN, REMOVE_USER, EDIT_USER, ADD_LIST, ADD_PLANT, REMOVE_PLANT, DELETE_LIST, SEARCH_PLANTS };
